---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: time-service
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: time-service
  interval: 30s
  releaseName: time-service
  targetNamespace: default
  values:
    image:
      tag: 0.1.0
