---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
        namespace: kube-system
  interval: 30m
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  # https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml
  values:
    image:
      tag: 1.1.3
    clusterName: eks-prod-us-west-2
